development:
  adapter: postgresql
  encoding: unicode
  database: jwilsco_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: jwilsco_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: jwilsco_production
  pool: 5
  username: postgres
  password: postgres
